### ISSUE TITLE
week-5 readme broken link

### ISSUE THREAD

**Issue by aulasau** [yandexdataschool/nlp_course#107]
In readme file of the week-5 link to the Huggingface quickstart tutorial is broken
<img width="427" alt="image" src="https://user-images.githubusercontent.com/17138883/200825563-2bf2c214-f9a1-4a24-9574-de49412ce6a5.png">

**Comment by poedator** [comment]
The `quick start` link existed in docs of Transformers versions up to 2.x.x
In the present doc, the [quick tour](https://huggingface.co/docs/transformers/quicktour) looks like a valid replacement.
