### ISSUE TITLE
solution

### ISSUE THREAD

**Issue by myk12** [yandexdataschool/nlp_course#109]
Are there any resolutions provided for the homework and Where can I find them?

Thanks~

**Comment by poedator** [comment]
These homeworks are like small research projects and there is no single perfect answer to share. Besides, to avoid spoilers for the future students we do not encourage public sharing of homework results.

**Comment by myk12** [comment]
I Get it, thanks~

**Comment by myk12** [comment]
> These homeworks are like small research projects and there is no single perfect answer to share. Besides, to avoid spoilers for the future students we do not encourage public sharing of homework results.

I get it, thanks~
