### ISSUE TITLE
A question of bow_vocabulary in w2_homework_part1

### ISSUE THREAD

**Issue by ZequnZ** [yandexdataschool/nlp_course#113]
Greetings,

I am working on the week2 homework(part1) notebook and have question about `bow_vocabulary`, as the length of the `bow_vocabulary` I created is different from the `length of the set of all tokens` in the training set. 
See the screenshot below:
<img width="705" alt="image" src="https://user-images.githubusercontent.com/58477055/218123812-14124c51-af75-4dc0-ac42-69249e24347e.png">

The way I created `bow_vocabulary` as follows:  
Basically like the idea of week1, I split the text with " "(space) which are the tokens generated from `TweetTokenizer`.  
Then I count the occurrence of each token and only keep the top `k` words in the vocabulary.
<img width="774" alt="image" src="https://user-images.githubusercontent.com/58477055/218124076-2411af3a-9574-4849-a192-c3f56c338e19.png">

When putting all tokens into a `set`, some tokens(str) would be treated as the same one so that the length decreases.   
I am wondering:
1. Is my way creating `bow_vocabulary` correct?
2. My understanding is that we should keep and use tokens from tokenizer, such that the creation of vocabulary is like: tokens -> vocabulary.  
However, I also understand that some string might be meaningless(with symbols only for example) and we can merge them together, like the `set` used in notebook. So creation of vocabulary is like: tokens -> pre-processing -> vocabulary.   
Could you shed some light on this? That would be super helpful!

Thanks for your time to look at this and I am looking forward to hearing your reply!

**Comment by poedator** [comment]
thank you for your interest to the course.
we do not provide public feedback on homework solutions here, since this creates unwanted spoilers.
