### ISSUE TITLE
requirement.txt

### ISSUE THREAD

**Issue by keyuchen21** [yandexdataschool/nlp_course#116]
will that be possible to get a requirement.txt? 
since in the install instruction there are no specific version of python, genism been mentioned, I constantly getting some bugs.

Thank you!!!

**Comment by poedator** [comment]
there is no single `requirement.txt` for the course, as the materials are regularly updated.
Unless specific version is suggested, you should be fine with the latest versions of the packages.
 
If you see a specific version problem, please submit an issue, or, better yet, a PR.
