### ISSUE TITLE
week 3, seminar, Kneser-Ney smoothing formula

### ISSUE THREAD

**Issue by ilivans** [yandexdataschool/nlp_course#12]
There must be a bug in Kneser-Ney smoothing formula
![image](https://user-images.githubusercontent.com/19606164/46474329-442f6980-c7eb-11e8-91ef-1101ba99e733.png)
The denominator shouldn't contain a subtraction of delta from counts. First of all, denominator becomes 0 in some cases. Also there is no delta in denominator at the lecture slides and wiki page.

**Comment by justheuristic** [comment]
Thanks! Will fix it right away
