### ISSUE TITLE
Missing word in text about residual connections

### ISSUE THREAD

**Issue by elyovin** [yandexdataschool/nlp_course#147]
![Screenshot from 2024-02-13 14-49-43](https://github.com/yandexdataschool/nlp_course/assets/26802814/28f68283-7c9a-473c-bc34-0186528b18ac)
Missing "have" in sentence:  A network can {have} several such blocks
Link: https://lena-voita.github.io/nlp_course/models/convolutional.html
Great course btw.

**Comment by poedator** [comment]
passing the message to @lena-voita
