### ISSUE TITLE
NB: there is a single NaN value in the Week2 seminar dataset

### ISSUE THREAD

**Issue by SaulAryehKohn** [yandexdataschool/nlp_course#15]
Make sure to get rid of it! It's in the "Salary" category, and will kill your embedding/CNN/regression training.

**Comment by justheuristic** [comment]
Thank you! We'll fix that. 

Just in case someone else is reading this: for now, please use [.dropna](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.dropna.html)
