### ISSUE TITLE
Week02 seminar Kneser–Ney smoothing

### ISSUE THREAD

**Issue by LB-Yu** [yandexdataschool/nlp_course#30]
Hi!
I have a problem of the Kneser-Ney smoothing formula. The formula for calculating *lambda* on the slide is shown below.<br>
![](https://user-images.githubusercontent.com/44154062/58469075-5e023000-8171-11e9-8942-b97fdca2eee6.png)<br>
What is the difference between the part 1 and the  part 2? I think they both calculated the number of times *w_i-n+1, ... ,w_i-1* and *w_i* co-occur.
And the formula on wiki page is:
![](https://user-images.githubusercontent.com/44154062/58469847-f1883080-8172-11e9-80ba-5fa193d2dca1.png)

**Comment by justheuristic** [comment]
(terribly sorry for the delay)
The N+1 term stands for the number of successor words with nonzero counts, as depicted on the slide in the previous formula. Here's the full slide

![img](https://i.imgur.com/nlDRB0W.png)

**Comment by justheuristic** [comment]
Feel free to reopen if you have further questions... if you still remember this exists
