### ISSUE TITLE
A delta typo

### ISSUE THREAD

**Issue by AdityaSoni19031997** [yandexdataschool/nlp_course#64]
First of all, Thanks a lot for your great website! Really hats off!

In the [link](https://lena-voita.github.io/nlp_course/text_classification.html#generative_discriminative), generative should be discriminative in the second bullet point.

Apologies for opening an issue for a very small thing.
Thanks.

**Comment by lena-voita** [comment]
You are right - thank you a lot for the help! Fixed.

Best,
Lena.
