### ISSUE TITLE
week04_seq2seq seminar link

### ISSUE THREAD

**Issue by vvs1984** [yandexdataschool/nlp_course#67]
Спасибо за курс, очень нравится и подача материала и уровень сложности.
В 4-й неделе есть небольшая ошибка -  [ссылка на запись семинара ветке  2020](https://yadi.sk/i/1pSImQdxA1_eaw)   относится к третьей неделе (Language Modeling)

**Comment by justheuristic** [comment]
мы очнулись от векового сна и всё починили, спасибо!
