### ISSUE TITLE
[question] tools for creating graphics

### ISSUE THREAD

**Issue by iharh** [yandexdataschool/nlp_course#83]
Hello.
Could you tell, what tool did you use for creating such beautiful graphics?

**Comment by DragonistYJ** [comment]
您好，我已经收到您的周报，周报收取截止时间为每周二下午八点，八点后将截止收取，请按时发送您的周报，谢谢！

**Comment by yuboona** [comment]
您的邮件我已收到，将尽快回复！！

**Comment by poedator** [comment]
the above replies translate to:
```
Hello, I have received your weekly report. The deadline for collecting the weekly report is 8:00 pm every Tuesday. Collection will be closed after 8:00. Please send your weekly report on time. Thank you!

I have received your email and will reply as soon as possible! !
```
looks like unintended messages.

to the OP: if still relevant, pls resubmit with the reference to the specific image.
