### ISSUE TITLE
is there any discussion group?

### ISSUE THREAD

**Issue by ericg108** [yandexdataschool/nlp_course#85]
Hi there,
This course is a terrific material to learn NLP from scratch with Pytorch/TensorFlow.
But I have a problem that I don't know if I am coding right or wrong when I finish the homework.
Is there any discussion group for learners to discuss or verify if we are coding right?

Thanks in advance.

**Comment by Extremesarova** [comment]
I'd like to participate in such group too

**Comment by poedator** [comment]
This repo material used for NLP class in Yandex School of Data Analysis. While your interest is appreciated, there is currently no chat open for non-YSDA students.
