### ISSUE TITLE
download data... 403 Forbidden

### ISSUE THREAD

**Issue by zheheng-dai** [yandexdataschool/nlp_course#86]
![cannot download](https://user-images.githubusercontent.com/60458836/177933626-6bdaae05-bbcc-465b-8525-1e8ed3d4e0a5.PNG)

**Comment by poedator** [comment]
https://ysda-seminars.s3.eu-central-1.amazonaws.com/Train_rev1.zip
this is a link from [Week-2 seminar](https://github.com/yandexdataschool/nlp_course/blob/2023/week02_classification/seminar.ipynb). I just tested it and it works OK. 
To exclude geofencing issues, if the problem persists, try downloading via VPN.

**Comment by chistotinsa** [comment]
> https://ysda-seminars.s3.eu-central-1.amazonaws.com/Train_rev1.zip this is a link from [Week-2 seminar](https://github.com/yandexdataschool/nlp_course/blob/2023/week02_classification/seminar.ipynb). I just tested it and it works OK. To exclude geofencing issues, if the problem persists, try downloading via VPN.

Just tried a VPN, it doesn`t solve the problem. It worked good even without VPN several days ago.

**Comment by poedator** [comment]
> Just tried a VPN, it doesn`t solve the problem. It worked good even without VPN several days ago.
Apparently there is some instability in AWS. Please use the alternative link from the same seminar notebook: https://yadi.sk/d/vVEOWPFY3NruT7
